# Generated by Django 6.0 on 2026-04-08 08:21

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_chuong', models.PositiveIntegerField()),
                ('ten', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['so_chuong'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ Email')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('chuong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='doctruyen.chuong')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='doctruyen.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('hide_phone', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='doctruyen.profile')),
            ],
            options={
                'verbose_name': 'Liên kết mạng xã hội',
                'verbose_name_plural': 'Các liên kết mạng xã hội',
            },
        ),
        migrations.CreateModel(
            name='Truyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_type', models.CharField(blank=True, choices=[('translated', 'Truyện dịch'), ('original', 'Truyện sáng tác'), ('ai', 'Truyện AI dịch')], default='translated', max_length=20, null=True)),
                ('ten', models.CharField(max_length=200)),
                ('tac_gia', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
                ('anh', models.ImageField(blank=True, null=True, upload_to='truyen/')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('ngay_dang', models.DateField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('ongoing', 'Đang cập nhật'), ('hoan_thanh', 'Hoàn thành'), ('tam_ngung', 'Tạm ngưng')], default='ongoing', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truyen_da_dang', to=settings.AUTH_USER_MODEL)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='truyen_hop_tac', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, related_name='truyens', to='doctruyen.genre')),
            ],
            options={
                'ordering': ['-ngay_dang'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly_do', models.TextField()),
                ('trang_thai', models.CharField(choices=[('pending', 'Chờ xử lý'), ('resolved', 'Đã xử lý'), ('rejected', 'Đã bác bỏ')], default='pending', max_length=20)),
                ('ghi_chu_admin', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('chuong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctruyen.chuong')),
                ('user_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='doctruyen.truyen')),
            ],
            options={
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.CharField(max_length=255)),
                ('loai', models.CharField(choices=[('like_comment', 'Like bình luận'), ('reply_comment', 'Reply bình luận'), ('mention_comment', 'Mention trong bình luận'), ('new_chapter', 'Chương mới'), ('new_follow', 'Follow mới'), ('transfer', 'Yêu cầu chuyển quyền'), ('share', 'Yêu cầu chia sẻ quyền'), ('delete_request', 'Yêu cầu xóa truyện')], max_length=20)),
                ('da_doc', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('ACCEPTED', 'Đã chấp nhận'), ('DECLINED', 'Đã từ chối')], default='PENDING', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('chuong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctruyen.chuong')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctruyen.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('user_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('truyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctruyen.truyen')),
            ],
            options={
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='doctruyen.truyen'),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_volume', models.PositiveIntegerField()),
                ('ten', models.CharField(blank=True, max_length=200)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='doctruyen.truyen')),
            ],
            options={
                'ordering': ['so_volume'],
                'unique_together': {('truyen', 'so_volume')},
            },
        ),
        migrations.AddField(
            model_name='chuong',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chuongs', to='doctruyen.volume'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('chuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='doctruyen.chuong')),
            ],
            options={
                'unique_together': {('user', 'chuong')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='doctruyen.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.PositiveIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')])),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='doctruyen.truyen')),
            ],
            options={
                'unique_together': {('truyen', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LichSuDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('chuong_vua_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctruyen.chuong')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctruyen.truyen')),
            ],
            options={
                'ordering': ['-ngay_cap_nhat'],
                'unique_together': {('user', 'truyen')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_theo_doi', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='doctruyen.truyen')),
            ],
            options={
                'unique_together': {('user', 'truyen')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chuong',
            unique_together={('volume', 'so_chuong')},
        ),
    ]
