# Generated by Django 6.0 on 2026-04-16 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truyen',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truyen_da_dang', to=settings.AUTH_USER_MODEL),
        ),
    ]
