# Generated by Django 6.0 on 2025-12-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truyen',
            name='anh',
            field=models.ImageField(blank=True, null=True, upload_to='truyen/'),
        ),
    ]
