# Generated by Django 6.0 on 2026-04-28 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0002_alter_truyen_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truyen',
            options={},
        ),
        migrations.AddField(
            model_name='truyen',
            name='latest_chap_number',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='truyen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='truyen',
            name='view_thang',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='truyen',
            name='view_tong',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='truyen',
            name='view_tuan',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='chuong',
            name='so_chuong',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='ngay_dang',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ViewStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='doctruyen.truyen')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('truyen', 'date')},
            },
        ),
    ]
