# Generated by Django 6.0 on 2026-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0003_alter_truyen_options_truyen_latest_chap_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuong',
            name='so_chuong',
            field=models.IntegerField(),
        ),
    ]
