# Generated by Django 6.0 on 2026-01-17 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0004_chuong_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='truyen',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='truyen_da_dang', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truyen',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='truyen_duoc_uy_quyen', to=settings.AUTH_USER_MODEL),
        ),
    ]
