# Generated by Django 6.0 on 2026-05-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0004_alter_chuong_so_chuong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-is_pinned', 'ngay_tao']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='doctruyen.comment'),
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
