# Generated by Django 6.0 on 2026-01-26 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0010_truyen_trang_thai_commentreply_notification_bookmark_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-is_pinned', '-ngay_tao']},
        ),
        migrations.AddField(
            model_name='comment',
            name='chuong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='doctruyen.chuong'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='ngay_chinh_sua',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='loai',
            field=models.CharField(choices=[('like_comment', 'Like bình luận'), ('reply_comment', 'Reply bình luận'), ('mention_comment', 'Mention trong bình luận'), ('new_chapter', 'Chương mới'), ('new_follow', 'Follow mới')], max_length=20),
        ),
    ]
