# Generated by Django 6.0 on 2026-03-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0011_alter_comment_options_comment_chuong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truyen',
            name='trang_thai',
            field=models.CharField(choices=[('ongoing', 'Đang cập nhật'), ('hoan_thanh', 'Hoàn thành'), ('tam_ngung', 'Tạm ngưng')], default='dang_ra', max_length=20),
        ),
    ]
