# Generated by Django 6.0 on 2026-03-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0012_alter_truyen_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='truyen',
            name='story_type',
            field=models.CharField(blank=True, choices=[('translated', 'Truyện dịch'), ('original', 'Truyện sáng tác'), ('ai', 'Truyện AI dịch')], default='translated', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='trang_thai',
            field=models.CharField(choices=[('ongoing', 'Đang cập nhật'), ('hoan_thanh', 'Hoàn thành'), ('tam_ngung', 'Tạm ngưng')], default='ongoing', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='chuong',
            unique_together={('volume', 'so_chuong')},
        ),
    ]
