# Generated by Django 6.0 on 2026-03-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0014_profile_gmail_profile_hide_gmail_profile_hide_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hide_gmail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hide_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='truyen',
            name='story_type',
        ),
        migrations.AlterField(
            model_name='truyen',
            name='trang_thai',
            field=models.CharField(choices=[('dang_ra', 'Đang ra'), ('hoan_thanh', 'Hoàn thành'), ('tam_ngung', 'Tạm ngưng')], default='dang_ra', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='chuong',
            unique_together={('volume', 'slug')},
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
