# Generated by Django 6.0 on 2026-03-02 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0015_remove_profile_gmail_remove_profile_hide_gmail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gmail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_gmail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='truyen',
            name='story_type',
            field=models.CharField(blank=True, choices=[('translated', 'Truyện dịch'), ('original', 'Truyện sáng tác'), ('ai', 'Truyện AI dịch')], default='translated', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='trang_thai',
            field=models.CharField(choices=[('ongoing', 'Đang cập nhật'), ('hoan_thanh', 'Hoàn thành'), ('tam_ngung', 'Tạm ngưng')], default='ongoing', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='chuong',
            unique_together={('volume', 'so_chuong')},
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='doctruyen.profile')),
            ],
            options={
                'verbose_name': 'Liên kết mạng xã hội',
                'verbose_name_plural': 'Các liên kết mạng xã hội',
            },
        ),
    ]
