# Generated by Django 6.0 on 2026-03-04 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0016_profile_gmail_profile_hide_gmail_profile_hide_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('ACCEPTED', 'Đã chấp nhận'), ('DECLINED', 'Đã từ chối')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='truyen',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='truyen_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='loai',
            field=models.CharField(choices=[('like_comment', 'Like bình luận'), ('reply_comment', 'Reply bình luận'), ('mention_comment', 'Mention trong bình luận'), ('new_chapter', 'Chương mới'), ('new_follow', 'Follow mới'), ('transfer', 'Yêu cầu chuyển quyền'), ('share', 'Yêu cầu chia sẻ quyền'), ('delete_request', 'Yêu cầu xóa truyện')], max_length=20),
        ),
    ]
