# Generated by Django 6.0 on 2026-03-10 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0017_notification_status_truyen_collaborators_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly_do', models.TextField(help_text='Lý do vi phạm (Nội dung thô tục, bản quyền, v.v.)')),
                ('trang_thai', models.CharField(choices=[('pending', 'Chờ xử lý'), ('resolved', 'Đã xử lý'), ('rejected', 'Đã bác bỏ')], default='pending', max_length=20)),
                ('ghi_chu_admin', models.TextField(blank=True, help_text='Phản hồi từ admin', null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('chuong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctruyen.chuong')),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='doctruyen.truyen')),
                ('user_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo cáo vi phạm',
                'verbose_name_plural': 'Các báo cáo vi phạm',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
