# Generated by Django 6.0 on 2026-03-17 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0018_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truyen',
            name='editors',
        ),
        migrations.AlterField(
            model_name='notification',
            name='truyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctruyen.truyen'),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='truyen_hop_tac', to=settings.AUTH_USER_MODEL),
        ),
    ]
