# Generated by Django 6.0 on 2026-03-17 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0019_remove_truyen_editors_alter_notification_truyen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='truyen',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='truyen_duoc_uy_quyen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='truyen',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='truyen_collaborations', to=settings.AUTH_USER_MODEL),
        ),
    ]
