# Generated by Django 6.0 on 2026-03-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0020_truyen_editors_alter_truyen_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='truyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctruyen.truyen'),
        ),
    ]
