# Generated by Django 6.0 on 2026-03-17 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0021_alter_notification_truyen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truyen',
            name='editors',
        ),
        migrations.AlterField(
            model_name='truyen',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='ruyen_duoc_uy_quyen', to=settings.AUTH_USER_MODEL),
        ),
    ]
