# Generated by Django 6.0 on 2026-03-17 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0022_remove_truyen_editors_alter_truyen_collaborators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='truyen',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='truyen_hop_tac', to=settings.AUTH_USER_MODEL),
        ),
    ]
