# Generated by Django 6.0 on 2025-12-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('tac_gia', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('ngay_dang', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Truyện',
                'verbose_name_plural': 'Truyện',
                'ordering': ['-ngay_dang'],
            },
        ),
    ]
