# Generated by Django 6.0 on 2026-01-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0002_truyen_anh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='truyen',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='truyens', to='doctruyen.genre'),
        ),
    ]
