# Generated by Django 6.0 on 2026-01-17 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0003_genre_truyen_genres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_chuong', models.PositiveIntegerField()),
                ('ten', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuongs', to='doctruyen.truyen')),
            ],
            options={
                'verbose_name': 'Chương',
                'verbose_name_plural': 'Chương',
                'ordering': ['so_chuong'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='doctruyen.truyen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
