# Generated by Django 6.0 on 2026-01-19 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0005_truyen_author_truyen_editors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('chuong_vua_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctruyen.chuong')),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctruyen.truyen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_xem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ngay_cap_nhat'],
                'unique_together': {('user', 'truyen')},
            },
        ),
    ]
