# Generated by Django 6.0 on 2026-01-21 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0006_lichsudoc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chuong',
            options={'ordering': ['so_chuong']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-ngay_tao']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='truyen',
            options={'ordering': ['-ngay_dang']},
        ),
        migrations.AlterField(
            model_name='chuong',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='lichsudoc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_volume', models.PositiveIntegerField()),
                ('ten', models.CharField(blank=True, max_length=200)),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='doctruyen.truyen')),
            ],
            options={
                'ordering': ['so_volume'],
                'unique_together': {('truyen', 'so_volume')},
            },
        ),
        migrations.AddField(
            model_name='chuong',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chuongs', to='doctruyen.volume'),
        ),
        migrations.AlterUniqueTogether(
            name='chuong',
            unique_together={('volume', 'slug')},
        ),
        migrations.RemoveField(
            model_name='chuong',
            name='truyen',
        ),
    ]
