# Generated by Django 6.0 on 2026-01-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctruyen', '0007_alter_chuong_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='mo_ta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
